### ISSUE TITLE
hello-world.ngfactory is missing from the repo.

### ISSUE THREAD

**Issue by eyassud** [SharePoint/sp-dev-fx-angular#1]
hello-world.ngfactory is missing.

import { HelloWorldModuleNgFactory } from "./hello-world.ngfactory";

**Comment by panjkov** [comment]
Hi @eyassud, 
Check out this question on StackOverflow - there you can see how to generate ngfactory file https://stackoverflow.com/questions/46122313/how-should-i-generate-the-app-module-ngfactory-ts-file  
but also, from Angular 5, compiler is not generating ngfactory files any more, as referenced here https://github.com/angular/angular/issues/20219
https://github.com/angular/angular/issues/19478

**Comment by robwormald** [comment]
This is automatically generated as it goes through the angular compiler - have a look at the gulpfile

**Comment by VesaJuvonen** [comment]
We are archiving this repository. If you are interested in seeing the latest sample around the SharePoint Framework Angular Elements usage, please see the following sample - https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/angularelements-helloworld.
