### ISSUE TITLE
solution is broken - web parts dont load

### ISSUE THREAD

**Issue by nigel-dewar** [SharePoint/sp-dev-fx-angular#5]
gulp does some build process but doesnt load any workbench. So used gulp serve.

Then when you try to add a web part, something adds but nothing shows

![image](https://user-images.githubusercontent.com/9402456/34910845-2c176dfe-f909-11e7-9ad3-489a295a62d4.png)

then when trying to load the GraphDemo part, I get this error

![image](https://user-images.githubusercontent.com/9402456/34910852-44dbaf3a-f909-11e7-8257-39832ee7e35f.png)

Browser = Chome
Platform = Windows 10 x64bit
node : 6.15.5

**Comment by huynp** [comment]
I run into the same problem. Anyone know how to fix it.

**Comment by VesaJuvonen** [comment]
We are archiving this repository. If you are interested in seeing the latest sample around the SharePoint Framework Angular Elements usage, please see the following sample - https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/angularelements-helloworld.
