### ISSUE TITLE
Getting issue when using gulp serve

### ISSUE THREAD

**Issue by gauravgoyal5** [SharePoint/sp-dev-fx-angular#6]
I have downloaded the code & run command npm install.
Then I tryied to use gulp serve command. When I am adding web part on workbench I am getting following error : 
![image](https://user-images.githubusercontent.com/6926513/37950414-053743b8-31b6-11e8-844f-6859d38987ca.png)

**Comment by VesaJuvonen** [comment]
We are archiving this repository. If you are interested in seeing the latest sample around the SharePoint Framework Angular Elements usage, please see the following sample - https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/angularelements-helloworld.
